# Generated by Django 4.1.4 on 2023-03-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
